_commit: v1.12.1-6-gbf0c0a5
_src_path: /Users/crthomas/code/charlesthomas/homelab-template
additionalResources: cluster-issuer.yaml
backups: false
helm: true
helmCrds: true
helmName: cert-manager
helmRelease: cert-manager
helmRepo: https://charts.jetstack.io
helmValues: helm/values.yaml
helmVersion: v1.13.2
homepageEnabled: false
ingress: false
labels: 'app.kubernetes.io/instance: cert-manager'
name: cert-manager
namespace: cert-manager
pvc: false
reloader: false
resources:
- external-secrets.yaml
service: false
serviceAccount: false
upstreamURL: https://cert-manager.io/
url: https://github.com/charlesthomas/homelab-cert-manager
