---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-cert-manager
commonLabels:
  app.kubernetes.io/instance: cert-manager

resources:
- resources/cluster-issuer.yaml
- resources/external-secrets.yaml
- resources/namespaces.yaml

helmCharts:
- name: cert-manager
  includeCRDs: true
  namespace: cert-manager
  releaseName: cert-manager
  repo: https://charts.jetstack.io
  valuesFile: helm/values.yaml
  version: v1.13.2
