---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-cert-manager
commonLabels:
  app.kubernetes.io/instance: cert-manager

resources:
- resources/cluster-issuer.yaml
- resources/external-secrets.yaml
- resources/namespaces.yaml
<<<<<<< before updating

=======
patches:
- patch: |-
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: cert-manager
      namespace: cert-manager
      annotations:
        gethomepage.dev/href: https://cert-manager.crt.house
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: 
        gethomepage.dev/group: 
        gethomepage.dev/icon: cert-manager
        gethomepage.dev/name: cert-manager
        gethomepage.dev/pod-selector: ""
  target:
    kind: Ingress
>>>>>>> after updating
helmCharts:
- name: cert-manager
  includeCRDs: true
  namespace: cert-manager
  releaseName: cert-manager
  repo: https://charts.jetstack.io
  valuesFile: helm/values.yaml
  version: v1.13.2
